name: Deploy Dockerized Test Laravel App On AWS EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t kodevendor/dockerized-test-laravel-app  .
      - name: Publish Image to docker hub
        run: docker push kodevendor/dockerized-test-laravel-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull kodevendor/dockerized-test-laravel-app:latest
      - name: Delete old container
        run: docker rm -f dockerized_test_laravel_app_container
      - name: Run Docker Container
        run: docker run -d -p 9000:80 --name dockerized_test_laravel_app_container kodevendor/dockerized-test-laravel-app
